apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app 
    spec:
      containers:
      - name: my-node-app
        image: chendureddy/my-node-app:latest
        ports:
        - containerPort: 3000
