apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: nodeserver
        image: chendureddy/my-node-app:latest
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: my-node-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
